import type { Event, Category } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  { _id: "m-cat-1", title: "Musica", slug: { current: "musica" }, icon: "Music2", color: "#E84C3D" },
  { _id: "m-cat-2", title: "Teatro", slug: { current: "teatro" }, icon: "Drama", color: "#8B5CF6" },
  { _id: "m-cat-3", title: "Sport", slug: { current: "sport" }, icon: "Trophy", color: "#F59E0B" },
  { _id: "m-cat-4", title: "Sagre", slug: { current: "sagre" }, icon: "Utensils", color: "#10B981" },
  { _id: "m-cat-5", title: "Cultura", slug: { current: "cultura" }, icon: "Landmark", color: "#06B6D4" },
  { _id: "m-cat-6", title: "Natura", slug: { current: "natura" }, icon: "TreePine", color: "#22C55E" },
];

export const MOCK_EVENTS: Event[] = [
  {
    _id: "mock-1",
    title: "Vasco Rossi – Vasco Live 2026",
    slug: { current: "vasco-rossi-live-2026" },
    date: "2026-06-15T20:30:00.000Z",
    price: "da €55",
    isFeatured: true,
    isSoldOut: false,
    category: MOCK_CATEGORIES[0],
    venue: { name: "Arena della Vittoria", city: "Bari", province: "BA", address: "Piazza Mario Massimo, Bari" },
    shortDescription: "Il grande ritorno di Vasco Rossi in Puglia con il suo iconico live show.",
  },
  {
    _id: "mock-2",
    title: "Rigoletto – Opera Festival di Puglia",
    slug: { current: "rigoletto-opera-festival-2026" },
    date: "2026-06-22T21:00:00.000Z",
    price: "da €25",
    isFeatured: false,
    isSoldOut: false,
    category: MOCK_CATEGORIES[1],
    venue: { name: "Teatro Politeama Greco", city: "Lecce", province: "LE", address: "Viale Giuseppe Gallipoli, Lecce" },
    shortDescription: "Il capolavoro di Verdi in scena nel magnifico Teatro Politeama di Lecce.",
  },
  {
    _id: "mock-3",
    title: "Taranto F.C. vs SSC Bari – Serie C",
    slug: { current: "taranto-vs-bari-serie-c-2026" },
    date: "2026-06-08T18:00:00.000Z",
    price: "da €12",
    isFeatured: false,
    isSoldOut: false,
    category: MOCK_CATEGORIES[2],
    venue: { name: "Stadio Erasmo Iacovone", city: "Taranto", province: "TA", address: "Viale Virgilio, Taranto" },
    shortDescription: "Il derby pugliese più atteso della stagione. Forza Taranto!",
  },
  {
    _id: "mock-4",
    title: "Sagra del Polpo di Porto Cesareo",
    slug: { current: "sagra-polpo-porto-cesareo-2026" },
    date: "2026-07-04T18:30:00.000Z",
    price: "Ingresso libero",
    isFeatured: false,
    isSoldOut: false,
    category: MOCK_CATEGORIES[3],
    venue: { name: "Lungomare di Porto Cesareo", city: "Porto Cesareo", province: "LE", address: "Lungomare, Porto Cesareo" },
    shortDescription: "La tradizionale sagra estiva con degustazioni, musica e cultura locale.",
  },
  {
    _id: "mock-5",
    title: "Van Gogh Experience – Arte immersiva",
    slug: { current: "van-gogh-experience-bari-2026" },
    date: "2026-05-15T10:00:00.000Z",
    endDate: "2026-07-15T20:00:00.000Z",
    price: "da €15",
    isFeatured: false,
    isSoldOut: false,
    category: MOCK_CATEGORIES[4],
    venue: { name: "Fiera del Levante", city: "Bari", province: "BA", address: "Lungomare Starita, Bari" },
    shortDescription: "Un'esperienza immersiva di 360° nelle opere di Vincent Van Gogh.",
  },
  {
    _id: "mock-6",
    title: "Salento Summer Festival 2026",
    slug: { current: "salento-summer-festival-2026" },
    date: "2026-07-20T21:30:00.000Z",
    price: "da €35",
    isFeatured: true,
    isSoldOut: true,
    category: MOCK_CATEGORIES[0],
    venue: { name: "Piazza Sant'Oronzo", city: "Lecce", province: "LE", address: "Piazza Sant'Oronzo, Lecce" },
    shortDescription: "Tre giorni di musica sotto le stelle nel cuore barocco di Lecce.",
  },
  {
    _id: "mock-7",
    title: "Shakespeare sotto le stelle – A Midsummer Night's Dream",
    slug: { current: "shakespeare-sogno-mezza-estate-2026" },
    date: "2026-06-28T21:00:00.000Z",
    price: "da €18",
    isFeatured: false,
    isSoldOut: false,
    category: MOCK_CATEGORIES[1],
    venue: { name: "Anfiteatro Arpi", city: "Foggia", province: "FG", address: "Via Arpi, Foggia" },
    shortDescription: "La commedia più amata di Shakespeare in un suggestivo anfiteatro romano.",
  },
  {
    _id: "mock-8",
    title: "Trekking dei Trulli – Valle d'Itria",
    slug: { current: "trekking-trulli-valle-itria-2026" },
    date: "2026-07-05T07:00:00.000Z",
    price: "€8",
    isFeatured: false,
    isSoldOut: false,
    category: MOCK_CATEGORIES[5],
    venue: { name: "Piazza del Trullo", city: "Alberobello", province: "BA", address: "Piazza del Popolo, Alberobello" },
    shortDescription: "Escursione guidata tra i trulli patrimonio UNESCO, con degustazione finale.",
  },
];
